# Generated by Django 4.1.5 on 2023-01-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Detial',
        ),
    ]
