# Generated by Django 4.1.5 on 2023-01-10 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0002_rename_book_detial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=250)),
                ('website', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('jobType', models.CharField(max_length=250)),
                ('experience', models.CharField(max_length=250)),
                ('qualification', models.CharField(max_length=250)),
                ('Batch', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('point1', models.CharField(max_length=250)),
                ('point2', models.CharField(max_length=250)),
                ('point3', models.CharField(max_length=250)),
                ('point4', models.CharField(max_length=250)),
                ('point5', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Detial',
        ),
    ]
