# Generated by Django 4.1.5 on 2023-01-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0003_detail_delete_detial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='companyId',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
