# Generated by Django 4.1.5 on 2023-01-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0004_detail_companyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='id',
        ),
        migrations.AlterField(
            model_name='detail',
            name='companyId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
