# Generated by Django 4.1.5 on 2023-01-11 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Detail', '0005_remove_detail_id_alter_detail_companyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='companyDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
    ]
